### PR TITLE
Export all option

### PR DESCRIPTION
**Pull request by larowlan**
Same as #52 but against the 8.x-1.x branch

### CODE REVIEW

**Comment by larowlan** [comment]
Needs re-roll for conflicts against 8.x-1.x branch

**Comment by larowlan** [comment]
+1 after reroll

**Comment by andypost** [comment]
Filed issue https://www.drupal.org/node/2664864

**Comment by larowlan** [comment]
Thanks @andypost - can you rebase against 8.x-1.x and push?

**Comment by andypost** [comment]
done

**Pull request merged**
