### PR TITLE
Switched to Drupal_TI

### PR DESCRIPTION
**Pull request by LKS90**
This pull request changes the .travis.yml to use the Drupal_TI template from https://github.com/LionsAd/drupal_ti. Take a look at the diff, removing a lot of complicated code and replacing it with a call to the corresponding drupal_ci function.

### CODE REVIEW

**Comment by jibran** [comment]
O hell yeah! @LKS90+++++++++++++.

**Comment by larowlan** [comment]
Great cleanup - thanks!
Tests are failing though?

**Comment by LKS90** [comment]
> Tests are failing though?

Fixed now!
Had to squeeze
  `- echo "always_populate_raw_post_data=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini`
somewhere before drupal was installed.

**Comment by LKS90** [comment]
I don't like that HHVM fails because of the variable 5.6 needs, will try and make that variable conditional for 5.6.

**Comment by larowlan** [comment]
Thanks! Will merge in the morning

**Comment by fabianx-ai** [comment]
Can someone open an upstream PR / issue, I think we want the PHP 5.6 fix in drupal_ti itself. (with a hidden option to turn it off).

**Comment by LKS90** [comment]
I made the setting conditional, now the requirements check itself is probably broken since in HHVM `always_populate_raw_post_data` is a boolean, it can't be -1 like the requirements demand.

Can be committed like this.

**Comment by larowlan** [comment]
Thanks @LKS90 and @LionsAd

**Pull request merged**
