### PR TITLE
Added sdboyer/gliph depdendency

### PR DESCRIPTION
**Pull request by Berdir**
We can switch to the graph component in core, but let's add this as a quickfix :)

Works well in combination with composer_manager, for example.

### CODE REVIEW

**Comment by jibran** [comment]
Do we have to add composer_manager dependency in info file as well? Should we fix tests here? Also we have to add 5.6 to travis.yml

**Comment by jibran** [comment]
Fixes #41

**Comment by Berdir** [comment]
I don't think we should have a dependency on composer_manager. It's just one way to get the dependency. If you use composer to build drupal, you don't need it. But it needs to be added to .travis an initialized there, yes.

**Comment by jibran** [comment]
Lol this is green on 5.6 and not on 5.5

**Comment by Berdir** [comment]
It's not actually related to the php version, github api limits are the problem. retest on 5.6 fixed it but not on 5.5. The composer self-update seems to invalidate caches or so, but it doesn't work without that.

Rebased and merged the commits together, let's see.

**Comment by jibran** [comment]
+1 to merge.

**Comment by Berdir** [comment]
#45 was merged instead, works for me :)

**Pull request closed without merging**
